SELECT*
FROM PORTFOLIOPROJECT..CovidDeath$
ORDER BY 3,4;

SELECT
DATE,
TOTAL_CASES,
NEW_CASES,
TOTAL_DEATHS,
POPULATION
FROM CovidDeath$
ORDER BY 1,2;

--LOOKING AT TOTAL CASES VS TOTAL DEATHS
--SHOWS LIKELYHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY

SELECT
LOCATION,
DATE,
TOTAL_CASES,
TOTAL_DEATHS,
(TOTAL_DEATHS/total_cases)*100 AS DeathPercentage
FROM CovidDeath$
WHERE LOCATION = 'UNITED STATES'
ORDER BY 1,2;

--LOOKING AT TOTAL CASES VS POPULATION
--SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID

SELECT
LOCATION,
DATE,
TOTAL_CASES,
POPULATION,
(TOTAL_CASES/POPULATION)*100 AS PercentageOfPop
FROM CovidDeath$
WHERE LOCATION = 'UNITED STATES' 
ORDER BY 1,2;

--LOOKING AT COUNTRIES WITH THE HIGHEST INFECTION RATE COMPARED TO THE POPLUATION

SELECT
CONTINENT,
POPULATION,
MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT,
MAX((TOTAL_CASES/POPULATION))*100 AS PercentOfPopInfected
FROM CovidDeath$
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT, POPULATION
ORDER BY PercentOfPopInfected DESC;

--LOOKING AT THE COUNTRIES WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT
LOCATION,
MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTAL_DEATH_COUNT
FROM CovidDeath$
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

--BREAKING THINGS DOWN BY CONTINENT
--SHOWING THE CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT
CONTINENT,
MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTAL_DEATH_COUNT
FROM CovidDeath$
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTAL_DEATH_COUNT DESC;

--GLOBAL NUMBERS

SELECT
DATE,
SUM(NEW_CASES) AS TotalCases, 
SUM(CAST(NEW_DEATHS AS INT)) AS TotalDeaths,
SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DeathPercentage
FROM CovidDeath$
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY 1,2;

--LOOKING AT TOTAL POPULATION VS VACCINATIONS

SELECT
DEA.CONTINENT,
DEA.LOCATION,
DEA.DATE,
DEA.POPULATION,
VAC.NEW_Vaccinations,
SUM(CAST(VAC.NEW_Vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS RollingPeopleVaccinated
FROM PORTFOLIOPROJECT..CovidDeath$ DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS$ VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE 
WHERE DEA.CONTINENT IS NOT NULL 
ORDER BY 2,3
;

--USE CTE

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, RollingPeopleVaccinated)
AS(
SELECT
DEA.CONTINENT,
DEA.LOCATION,
DEA.DATE,
DEA.POPULATION,
VAC.NEW_Vaccinations,
SUM(CAST(VAC.NEW_Vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS RollingPeopleVaccinated
FROM PORTFOLIOPROJECT..CovidDeath$ DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS$ VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE 
WHERE DEA.CONTINENT IS NOT NULL 
)
SELECT*,
(ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS PCNTPOPVAC
FROM POPVSVAC
;

--TEMP TABLE

CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
    CONTINENT NVARCHAR(255),
    LOCATION NVARCHAR (255),
    DATE DATETIME,
    POPULATION NUMERIC,
    NEW_VACCINATIONS NUMERIC,
    ROLLINGPEOPLEVACCINATED NUMERIC
)
INSERT INTO #PERCENTPOPULATIONVACCINATED

SELECT
DEA.CONTINENT,
DEA.LOCATION,
DEA.DATE,
DEA.POPULATION,
VAC.NEW_Vaccinations,
SUM(CAST(VAC.NEW_Vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS RollingPeopleVaccinated
FROM PORTFOLIOPROJECT..CovidDeath$ DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS$ VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE 
WHERE DEA.CONTINENT IS NOT NULL 

SELECT*, (ROLLINGPEOPLEVACCINATED/POPULATION)*100 
FROM #PERCENTPOPULATIONVACCINATED
;


--CREATING VIEW TO STORE DATA FOR LATER VISUALIZATIONS

CREATE VIEW PERCENTPOPULATIONVACCINATED AS 
SELECT
DEA.CONTINENT,
DEA.LOCATION,
DEA.DATE,
DEA.POPULATION,
VAC.NEW_Vaccinations,
SUM(CAST(VAC.NEW_Vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS RollingPeopleVaccinated
FROM PORTFOLIOPROJECT..CovidDeath$ DEA
JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS$ VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE 
WHERE DEA.CONTINENT IS NOT NULL 